name: shopping_list
description: "Shopping List lets you create your shopping lists and store your loyalty cards, even without an internet connection. This allows you to use it anywhere, easily and quickly."
publish_to: 'none'
version: 1.3.2+8 # versionCode+versionName

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  go_router: ^15.1.2
  hydrated_bloc: ^10.0.0
  google_fonts: ^6.2.1
  flutter_bloc: ^9.1.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  equatable: ^2.0.7
  fpdart: ^1.1.1
  bloc: ^9.0.0
  get_it: ^8.0.3
  barcode_widget: ^2.0.4
  flutter_barcode_scanner_plus: ^3.0.8
  easy_localization: ^3.0.7+1
  share_plus: ^11.0.0
  file_picker: ^10.1.9
  pretty_qr_code: ^3.4.0
  flutter_colorpicker: ^1.1.0
  flutter_switch: ^0.3.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
